potions:
  demo:
    type: splash
    display: '&aDemo' # display name of the potions item
    color: 'red' # what color of potion to display as the icon
    effects: # list of potion effects this will use
      jump: # name of potion effect goto github above to see list
        duration: 10 # time this effect lastest in seconds
        strength: 2 # the strength of the effect starting from 0
      slow_falling: # name of potion effect goto github above to see list
        duration: 10 # time this effect lastest in seconds
        strength: 0 # the strength of the effect starting from 0
